### ISSUE TITLE
Fetching stuff that do not have the correct extensions from the API returns nothing to the Scratch Console

### ISSUE THREAD

**Issue by Kaylerr** [Cube-Enix/Cube-Enix.github.io#1]
if the website doesn't end in .js, .txt or some other extension, Scratch decides not to return it 

@BlueFalconHD make your api have .txt or something on the end so i can grab it pls

**Comment by ShipmasterKyle** [comment]
This is an issue I've looked into. The new API will also have a problem. The issue is the usage of Fetch instead of xhttp. API can't be fetched. More info about it [here](https://www.w3schools.com/xml/xml_http.asp)
